version: "3.0"

services:
  adopet-service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: adopet-container
    env_file:
      - .env
    networks:
      - adopet-net
    depends_on:
      - db

  db:
    image: postgres:11
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - .env
    networks:
      - adopet-net

networks:
  adopet-net:
    name: adopet-net
    driver: bridge