version: "3.0"

services:
  adopet-revision:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    networks:
      - adopet-net
    volumes:
      - .:/app

  adopet-service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: adopet-container
    env_file:
      - .env
    networks:
      - adopet-net
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
    command: ["./start-for-local-development.sh"]

  integration-tests:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command:
      [
        "./scripts/start-tests.sh",
      ]
  db:
    image: postgres:11
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - .env
    networks:
      - adopet-net

  sonar-cli:
    container_name: sonarcli
    image: sonarsource/sonar-scanner-cli
    working_dir: /adopet
    platform: linux/amd64
    environment:
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=test
      - SONAR_HOST_URL=http://host.docker.internal:9000
    volumes:
      - .:/adopet
    command: [ "sonar-scanner", "--debug" ]
networks:
  adopet-net:
    name: adopet-net
    driver: bridge