version: "3.0"
services:
  adopet-service:
    build:
      dockerfile: Dockerfile
    container_name: adopet-container
    env_file:
      - .env
  db:
    image: postgres:11
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - .env