version: 1
disable_existing_loggers: False

filters:
  correlation_id:
    (): asgi_correlation_id.CorrelationIdFilter
    uuid_length: 32

formatters:
  timestamped:
    class: core.log_formatter.CustomFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: timestamped
    filters: [ correlation_id ]

root:
  level: INFO
  handlers: [ console ]

loggers:
  api:
    level: INFO
    handlers: [ console ]
    propagate: no

  core:
    level: INFO
    handlers: [ console ]
    propagate: no

  uvicorn.error:
    handlers: [ console ]
    level: ERROR
    propagate: no

  uvicorn.access:
    handlers: [ console ]
    level: INFO
    propagate: no

  uvicorn:
    handlers: [ console ]
    level: WARNING
    propagate: no

  logger_alembic:
    level: INFO
    handlers: [ console ]
