"""pet model

Revision ID: 80aeb6522db7
Revises: 371250f020b2
Create Date: 2023-04-26 20:10:57.077281

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "80aeb6522db7"
down_revision = "371250f020b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "pet",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("photo_url", sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column("personality", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("specie_id", sa.Uuid(), nullable=False),
        sa.Column("status_id", sa.Uuid(), nullable=False),
        sa.Column("size_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["adopet.city.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["adopet.user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["size_id"], ["adopet.size.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specie_id"], ["adopet.animalspecie.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["adopet.state.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["status_id"], ["adopet.status.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("photo_url"),
        schema="adopet",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
