"""user model

Revision ID: 371250f020b2
Revises: c97c583599cc
Create Date: 2023-04-26 20:09:02.529014

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "371250f020b2"
down_revision = "c97c583599cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "user",
        sa.Column("name", sa.String(length=155), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("about", sa.String(), nullable=False),
        sa.Column("photo_url", sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("photo_url"),
        schema="adopet",
    )
    op.create_index(
        op.f("ix_adopet_user_email"), "user", ["email"], unique=True, schema="adopet"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adopet_user_email"), table_name="user", schema="adopet")
    op.drop_table("user", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
