"""status model

Revision ID: c97c583599cc
Revises: f1a711334da4
Create Date: 2023-04-26 20:08:43.392049

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c97c583599cc"
down_revision = "f1a711334da4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "status",
        sa.Column(
            "name",
            sa.Enum(
                "NEW",
                "AVAILABLE",
                "ADOPET",
                "QUARANTINE",
                "REMOVED",
                "SUSPENDED",
                name="statusenum",
                schema="adopet",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
