"""size model

Revision ID: 85085d68e2e1
Revises: 5c5afc62f994
Create Date: 2023-04-26 20:07:35.322604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85085d68e2e1"
down_revision = "5c5afc62f994"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "size",
        sa.Column(
            "name",
            sa.Enum(
                "MINI",
                "SMALL",
                "MEDIUM",
                "LARGE",
                "GIANT",
                name="sizeenum",
                schema="adopet",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("size", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
