"""status model

Revision ID: ddfe58fc87eb
Revises: 9c0638fe4a61
Create Date: 2023-04-24 01:15:13.065455

"""
import sqlalchemy as sa
from alembic import op
from api.enums.status_enum import StatusEnum
from api.models.status_model import StatusModel

# revision identifiers, used by Alembic.
revision = "ddfe58fc87eb"
down_revision = "9c0638fe4a61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "status",
        sa.Column(
            "name",
            sa.Enum(
                "NEW",
                "AVAILABLE",
                "ADOPET",
                "QUARANTINE",
                "REMOVED",
                "SUSPENDED",
                name="statusenum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        StatusModel.__table__, [{"name": value.value} for value in StatusEnum]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
