"""pet model

Revision ID: 01fb7fa01d7c
Revises: 6627418e92a3
Create Date: 2023-04-24 01:19:27.226564

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "01fb7fa01d7c"
down_revision = "6627418e92a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "pet",
        sa.Column("photo_url", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("name", sa.String(length=155), nullable=False),
        sa.Column("personality", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("specie_id", sa.UUID(), nullable=True),
        sa.Column("status_id", sa.UUID(), nullable=True),
        sa.Column("size_id", sa.UUID(), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("city_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["adopet.city.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["adopet.user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["size_id"], ["adopet.size.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specie_id"], ["adopet.animal_specie.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["adopet.state.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["status_id"], ["adopet.status.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
