"""size model

Revision ID: 9c0638fe4a61
Revises: a6eb7cef308a
Create Date: 2023-04-24 01:12:44.248640

"""
import sqlalchemy as sa
from alembic import op
from api.enums.size_enum import SizeEnum
from api.models.size_model import SizeModel

# revision identifiers, used by Alembic.
revision = "9c0638fe4a61"
down_revision = "a6eb7cef308a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "size",
        sa.Column(
            "name",
            sa.Enum(
                "MINI",
                "SMALL",
                "MEDIUM",
                "LARGE",
                "GIANT",
                name="sizeenum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###
    op.bulk_insert(SizeModel.__table__, [{"name": value.value} for value in SizeEnum])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("size", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
