"""animal specie model

Revision ID: a6eb7cef308a
Revises: 82d08229a244
Create Date: 2023-04-24 01:09:45.814773

"""
import sqlalchemy as sa
from alembic import op
from api.enums.animal_species import AnimalSpecieEnum
from api.models.animal_specie_model import AnimalSpecieModel

# revision identifiers, used by Alembic.
revision = "a6eb7cef308a"
down_revision = "82d08229a244"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS adopet")
    op.create_table(
        "animal_specie",
        sa.Column(
            "name", sa.Enum("DOG", "CAT", name="animalspecieenum"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="adopet",
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        AnimalSpecieModel.__table__,
        [{"name": value.value} for value in AnimalSpecieEnum],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("animal_specie", schema="adopet")
    op.execute("DROP SCHEMA IF EXISTS adopet RESTRICT")
    # ### end Alembic commands ###
