"""fix user model

Revision ID: 3b7446acc15f
Revises: fe94ee4c8f66
Create Date: 2023-04-22 02:43:22.665511

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b7446acc15f"
down_revision = "fe94ee4c8f66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("photo_url", sqlalchemy_utils.types.url.URLType(), nullable=True),
    )
    op.create_unique_constraint(None, "user", ["password"])
    op.drop_column("user", "phot_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phot_url", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "photo_url")
    # ### end Alembic commands ###
