"""pet - user relationship

Revision ID: 7a4fefcaf57a
Revises: 3b7446acc15f
Create Date: 2023-04-22 02:50:17.869462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4fefcaf57a'
down_revision = '3b7446acc15f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
