"""size and status models

Revision ID: 993e09fc1bff
Revises: 0cc3c0c325c5
Create Date: 2023-04-21 21:05:25.474026

"""
import sqlalchemy as sa
from alembic import op
from api.enums.size_enum import SizeEnum
from api.enums.status_enum import StatusEnum
from api.models.size_model import SizeModel
from api.models.status_model import StatusModel

# revision identifiers, used by Alembic.
revision = "993e09fc1bff"
down_revision = "0cc3c0c325c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "size",
        sa.Column(
            "name",
            sa.Enum(
                "MINI",
                "SMALL",
                "MEDIUM",
                "LARGE",
                "GIANT",
                name="sizeenum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status",
        sa.Column(
            "name",
            sa.Enum(
                "NEW",
                "AVAILABLE",
                "ADOPET",
                "QUARANTINE",
                "REMOVED",
                "SUSPENDED",
                name="statusenum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        StatusModel.__table__, [{"name": value.value} for value in StatusEnum]
    )
    op.bulk_insert(SizeModel.__table__, [{"name": value.value} for value in SizeEnum])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status")
    op.drop_table("size")
    # ### end Alembic commands ###
