"""pet model

Revision ID: ca1ec2606c6f
Revises: 3b7446acc15f
Create Date: 2023-04-22 03:06:34.105028

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca1ec2606c6f"
down_revision = "3b7446acc15f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pet",
        sa.Column("photo_url", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("name", sa.String(length=155), nullable=False),
        sa.Column("personality", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("specie_id", sa.UUID(), nullable=True),
        sa.Column("status_id", sa.UUID(), nullable=True),
        sa.Column("size_id", sa.UUID(), nullable=True),
        sa.Column("state_id", sa.UUID(), nullable=True),
        sa.Column("city_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["size_id"], ["size.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specie_id"], ["animal_specie.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["state_id"], ["state.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_id"], ["status.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet")
    # ### end Alembic commands ###
